name: Deploy

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: REGISTRY,IMAGE_NAME,DB_USER,DB_PASSWORD,SERVICE_ID,TG_TOKEN
          script: |
            cd /home/apps/distributor
            docker compose pull
            docker compose up -d
